apiVersion: v1
kind: Pod
metadata:
  name: test-connection
spec:
  serviceAccountName: nginx-sa
  containers:
  - name: tester
    image: busybox:latest
    command: ['sh', '-c', 'wget -qO- http://nginx-service']
  restartPolicy: Never

