apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app-3
spec: 
  destination: 
    namespace: dev
    server: https://kubernetes.default.svc
  project: project-3
  source:
    helm:
      releaseName: application-from-helm
      valueFiles: 
        - custom-values.yaml
    path: v03-argocd-applications/helm/nginx
    repoURL: https://github.com/ShayGuedj-DevOps/argocd-deep-learning.git
    targetRevision: main

