apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-4
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'de*'
    server: '*'
  sourceRepos:
  - '*'
  - '*'
